<?php

namespace Lwwcas\LaravelCountries\Database\Seeders;

use Illuminate\Database\Seeder;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\AD_Andorra;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\AE_UnitedArabEmirates;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\AF_Afghanistan;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\AG_AntiguaandBarbuda;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\AI_Anguilla;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\AL_Albania;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\AM_Armenia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\AO_Angola;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\AQ_Antarctica;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\AR_Argentina;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\AS_AmericanSamoa;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\AT_Austria;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\AU_Australia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\AW_Aruba;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\AX_AlandIslands;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\AZ_Azerbaijan;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BA_BosniaandHerzegovina;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BB_Barbados;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BD_Bangladesh;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BE_Belgium;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BF_BurkinaFaso;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BG_Bulgaria;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BH_Bahrain;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BI_Burundi;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BJ_Benin;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BL_SaintBarthelemy;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BM_Bermuda;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BN_BruneiDarussalam;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BO_Bolivia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BR_Brazil;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BS_Bahamas;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BT_Bhutan;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BV_BouvetIsland;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BW_Botswana;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BY_Belarus;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\BZ_Belize;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CA_Canada;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CC_CocosKeelingIslands;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CD_CongoKinshasa;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CF_CentralAfricanRepublic;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CG_CongoBrazzaville;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CH_Switzerland;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CI_CotedIvoire;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CK_CookIslands;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CL_Chile;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CM_Cameroon;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CN_China;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CO_Colombia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CR_CostaRica;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CU_Cuba;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CV_CapeVerde;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CX_ChristmasIsland;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CY_Cyprus;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\CZ_CzechRepublic;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\DE_Germany;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\DJ_Djibouti;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\DK_Denmark;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\DM_Dominica;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\DO_DominicanRepublic;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\DZ_Algeria;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\EC_Ecuador;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\EE_Estonia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\EG_Egypt;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\EH_WesternSahara;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\ER_Eritrea;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\ES_Spain;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\ET_Ethiopia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\FI_Finland;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\FJ_Fiji;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\FK_FalklandIslands;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\FM_Micronesia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\FO_FaroeIslands;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\FR_France;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GA_Gabon;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GB_UnitedKingdom;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GD_Grenada;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GE_Georgia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GF_FrenchGuiana;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GG_Guernsey;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GH_Ghana;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GI_Gibraltar;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GL_Greenland;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GM_Gambia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GN_Guinea;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GP_Guadeloupe;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GQ_EquatorialGuinea;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GR_Greece;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GS_SouthGeorgiaandtheSouthSandwichIslands;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GT_Guatemala;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GU_Guam;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GW_GuineaBissau;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\GY_Guyana;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\HK_HongKongSARChina;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\HM_HeardIslandandMcDonaldIslands;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\HN_Honduras;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\HR_Croatia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\HT_Haiti;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\HU_Hungary;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\ID_Indonesia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\IE_Ireland;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\IL_Israel;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\IM_IsleofMan;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\IN_India;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\IO_BritishIndianOceanTerritory;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\IQ_Iraq;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\IR_Iran;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\IS_Iceland;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\IT_Italy;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\JE_Jersey;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\JM_Jamaica;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\JO_Jordan;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\JP_Japan;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\KE_Kenya;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\KG_Kyrgyzstan;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\KH_Cambodia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\KI_Kiribati;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\KM_Comoros;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\KN_SaintKittsandNevis;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\KP_NorthKorea;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\KR_SouthKorea;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\KW_Kuwait;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\KY_CaymanIslands;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\KZ_Kazakhstan;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\LA_LaoPDR;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\LB_Lebanon;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\LC_SaintLucia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\LI_Liechtenstein;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\LK_SriLanka;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\LR_Liberia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\LS_Lesotho;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\LT_Lithuania;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\LU_Luxembourg;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\LV_Latvia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\LY_Libya;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MA_Morocco;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MC_Monaco;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MD_Moldova;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\ME_Montenegro;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MF_SaintMartin;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MG_Madagascar;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MH_MarshallIslands;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MK_Macedonia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\ML_Mali;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MM_Myanmar;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MN_Mongolia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MO_MacauSARChina;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MP_NorthernMarianaIslands;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MQ_Martinique;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MR_Mauritania;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MS_Montserrat;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MT_Malta;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MU_Mauritius;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MV_Maldives;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MW_Malawi;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MX_Mexico;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MY_Malaysia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\MZ_Mozambique;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\NA_Namibia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\NC_NewCaledonia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\NE_Niger;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\NF_NorfolkIsland;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\NG_Nigeria;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\NI_Nicaragua;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\NL_Netherlands;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\NO_Norway;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\NP_Nepal;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\NR_Nauru;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\NU_Niue;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\NZ_NewZealand;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\OM_Oman;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\PA_Panama;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\PE_Peru;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\PF_FrenchPolynesia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\PG_PapuaNewGuinea;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\PH_Philippines;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\PK_Pakistan;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\PL_Poland;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\PM_SaintPierreandMiquelon;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\PN_PitcairnIslands;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\PR_PuertoRico;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\PS_PalestinianTerritory;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\PT_Portugal;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\PW_Palau;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\PY_Paraguay;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\QA_Qatar;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\RE_Reunion;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\RO_Romania;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\RS_Serbia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\RU_Russia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\RW_Rwanda;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SA_SaudiArabia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SB_SolomonIslands;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SC_Seychelles;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SD_Sudan;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SE_Sweden;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SG_Singapore;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SH_SaintHelena;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SI_Slovenia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SJ_SvalbardandJanMayen;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SK_Slovakia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SL_SierraLeone;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SM_SanMarino;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SN_Senegal;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SO_Somalia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SR_Suriname;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\ST_SaoTomeandPrincipe;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SV_ElSalvador;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SY_Syria;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\SZ_Swaziland;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\TC_TurksandCaicosIslands;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\TD_Chad;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\TF_FrenchSouthernTerritories;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\TG_Togo;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\TH_Thailand;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\TJ_Tajikistan;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\TK_Tokelau;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\TL_TimorLeste;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\TM_Turkmenistan;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\TN_Tunisia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\TO_Tonga;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\TR_Turkey;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\TT_TrinidadandTobago;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\TV_Tuvalu;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\TW_Taiwan;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\TZ_Tanzania;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\UA_Ukraine;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\UG_Uganda;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\UM_USMinorOutlyingIslands;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\US_UnitedStatesofAmerica;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\UY_Uruguay;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\UZ_Uzbekistan;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\VA_VaticanCity;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\VC_SaintVincentandGrenadines;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\VE_Venezuela;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\VG_BritishVirginIslands;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\VI_VirginIslandsUS;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\VN_Vietnam;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\VU_Vanuatu;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\WF_WallisandFutunaIslands;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\WS_Samoa;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\YE_Yemen;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\YT_Mayotte;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\ZA_SouthAfrica;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\ZM_Zambia;
use Lwwcas\LaravelCountries\Database\Seeders\Countries\ZW_Zimbabwe;

class LwwcasDatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // Regions Base
        $this->call(RegionsSeeder::class);

        // Countries Base
        $this->call(AD_Andorra::class);
        $this->call(AE_UnitedArabEmirates::class);
        $this->call(AF_Afghanistan::class);
        $this->call(AG_AntiguaandBarbuda::class);
        $this->call(AI_Anguilla::class);
        $this->call(AL_Albania::class);
        $this->call(AM_Armenia::class);
        $this->call(AO_Angola::class);
        $this->call(AQ_Antarctica::class);
        $this->call(AR_Argentina::class);
        $this->call(AS_AmericanSamoa::class);
        $this->call(AT_Austria::class);
        $this->call(AU_Australia::class);
        $this->call(AW_Aruba::class);
        $this->call(AX_AlandIslands::class);
        $this->call(AZ_Azerbaijan::class);
        $this->call(BA_BosniaandHerzegovina::class);
        $this->call(BB_Barbados::class);
        $this->call(BD_Bangladesh::class);
        $this->call(BE_Belgium::class);
        $this->call(BF_BurkinaFaso::class);
        $this->call(BG_Bulgaria::class);
        $this->call(BH_Bahrain::class);
        $this->call(BI_Burundi::class);
        $this->call(BJ_Benin::class);
        $this->call(BL_SaintBarthelemy::class);
        $this->call(BM_Bermuda::class);
        $this->call(BN_BruneiDarussalam::class);
        $this->call(BO_Bolivia::class);
        $this->call(BR_Brazil::class);
        $this->call(BS_Bahamas::class);
        $this->call(BT_Bhutan::class);
        $this->call(BV_BouvetIsland::class);
        $this->call(BW_Botswana::class);
        $this->call(BY_Belarus::class);
        $this->call(BZ_Belize::class);
        $this->call(CA_Canada::class);
        $this->call(CC_CocosKeelingIslands::class);
        $this->call(CD_CongoKinshasa::class);
        $this->call(CF_CentralAfricanRepublic::class);
        $this->call(CG_CongoBrazzaville::class);
        $this->call(CH_Switzerland::class);
        $this->call(CI_CotedIvoire::class);
        $this->call(CK_CookIslands::class);
        $this->call(CL_Chile::class);
        $this->call(CM_Cameroon::class);
        $this->call(CN_China::class);
        $this->call(CO_Colombia::class);
        $this->call(CR_CostaRica::class);
        $this->call(CU_Cuba::class);
        $this->call(CV_CapeVerde::class);
        $this->call(CX_ChristmasIsland::class);
        $this->call(CY_Cyprus::class);
        $this->call(CZ_CzechRepublic::class);
        $this->call(DE_Germany::class);
        $this->call(DJ_Djibouti::class);
        $this->call(DK_Denmark::class);
        $this->call(DM_Dominica::class);
        $this->call(DO_DominicanRepublic::class);
        $this->call(DZ_Algeria::class);
        $this->call(EC_Ecuador::class);
        $this->call(EE_Estonia::class);
        $this->call(EG_Egypt::class);
        $this->call(EH_WesternSahara::class);
        $this->call(ER_Eritrea::class);
        $this->call(ES_Spain::class);
        $this->call(ET_Ethiopia::class);
        $this->call(FI_Finland::class);
        $this->call(FJ_Fiji::class);
        $this->call(FK_FalklandIslands::class);
        $this->call(FM_Micronesia::class);
        $this->call(FO_FaroeIslands::class);
        $this->call(FR_France::class);
        $this->call(GA_Gabon::class);
        $this->call(GB_UnitedKingdom::class);
        $this->call(GD_Grenada::class);
        $this->call(GE_Georgia::class);
        $this->call(GF_FrenchGuiana::class);
        $this->call(GG_Guernsey::class);
        $this->call(GH_Ghana::class);
        $this->call(GI_Gibraltar::class);
        $this->call(GL_Greenland::class);
        $this->call(GM_Gambia::class);
        $this->call(GN_Guinea::class);
        $this->call(GP_Guadeloupe::class);
        $this->call(GQ_EquatorialGuinea::class);
        $this->call(GR_Greece::class);
        $this->call(GS_SouthGeorgiaandtheSouthSandwichIslands::class);
        $this->call(GT_Guatemala::class);
        $this->call(GU_Guam::class);
        $this->call(GW_GuineaBissau::class);
        $this->call(GY_Guyana::class);
        $this->call(HK_HongKongSARChina::class);
        $this->call(HM_HeardIslandandMcDonaldIslands::class);
        $this->call(HN_Honduras::class);
        $this->call(HR_Croatia::class);
        $this->call(HT_Haiti::class);
        $this->call(HU_Hungary::class);
        $this->call(ID_Indonesia::class);
        $this->call(IE_Ireland::class);
        $this->call(IL_Israel::class);
        $this->call(IM_IsleofMan::class);
        $this->call(IN_India::class);
        $this->call(IO_BritishIndianOceanTerritory::class);
        $this->call(IQ_Iraq::class);
        $this->call(IR_Iran::class);
        $this->call(IS_Iceland::class);
        $this->call(IT_Italy::class);
        $this->call(JE_Jersey::class);
        $this->call(JM_Jamaica::class);
        $this->call(JO_Jordan::class);
        $this->call(JP_Japan::class);
        $this->call(KE_Kenya::class);
        $this->call(KG_Kyrgyzstan::class);
        $this->call(KH_Cambodia::class);
        $this->call(KI_Kiribati::class);
        $this->call(KM_Comoros::class);
        $this->call(KN_SaintKittsandNevis::class);
        $this->call(KP_NorthKorea::class);
        $this->call(KR_SouthKorea::class);
        $this->call(KW_Kuwait::class);
        $this->call(KY_CaymanIslands::class);
        $this->call(KZ_Kazakhstan::class);
        $this->call(LA_LaoPDR::class);
        $this->call(LB_Lebanon::class);
        $this->call(LC_SaintLucia::class);
        $this->call(LI_Liechtenstein::class);
        $this->call(LK_SriLanka::class);
        $this->call(LR_Liberia::class);
        $this->call(LS_Lesotho::class);
        $this->call(LT_Lithuania::class);
        $this->call(LU_Luxembourg::class);
        $this->call(LV_Latvia::class);
        $this->call(LY_Libya::class);
        $this->call(MA_Morocco::class);
        $this->call(MC_Monaco::class);
        $this->call(MD_Moldova::class);
        $this->call(ME_Montenegro::class);
        $this->call(MF_SaintMartin::class);
        $this->call(MG_Madagascar::class);
        $this->call(MH_MarshallIslands::class);
        $this->call(MK_Macedonia::class);
        $this->call(ML_Mali::class);
        $this->call(MM_Myanmar::class);
        $this->call(MN_Mongolia::class);
        $this->call(MO_MacauSARChina::class);
        $this->call(MP_NorthernMarianaIslands::class);
        $this->call(MQ_Martinique::class);
        $this->call(MR_Mauritania::class);
        $this->call(MS_Montserrat::class);
        $this->call(MT_Malta::class);
        $this->call(MU_Mauritius::class);
        $this->call(MV_Maldives::class);
        $this->call(MW_Malawi::class);
        $this->call(MX_Mexico::class);
        $this->call(MY_Malaysia::class);
        $this->call(MZ_Mozambique::class);
        $this->call(NA_Namibia::class);
        $this->call(NC_NewCaledonia::class);
        $this->call(NE_Niger::class);
        $this->call(NF_NorfolkIsland::class);
        $this->call(NG_Nigeria::class);
        $this->call(NI_Nicaragua::class);
        $this->call(NL_Netherlands::class);
        $this->call(NO_Norway::class);
        $this->call(NP_Nepal::class);
        $this->call(NR_Nauru::class);
        $this->call(NU_Niue::class);
        $this->call(NZ_NewZealand::class);
        $this->call(OM_Oman::class);
        $this->call(PA_Panama::class);
        $this->call(PE_Peru::class);
        $this->call(PF_FrenchPolynesia::class);
        $this->call(PG_PapuaNewGuinea::class);
        $this->call(PH_Philippines::class);
        $this->call(PK_Pakistan::class);
        $this->call(PL_Poland::class);
        $this->call(PM_SaintPierreandMiquelon::class);
        $this->call(PN_PitcairnIslands::class);
        $this->call(PR_PuertoRico::class);
        $this->call(PS_PalestinianTerritory::class);
        $this->call(PT_Portugal::class);
        $this->call(PW_Palau::class);
        $this->call(PY_Paraguay::class);
        $this->call(QA_Qatar::class);
        $this->call(RE_Reunion::class);
        $this->call(RO_Romania::class);
        $this->call(RS_Serbia::class);
        $this->call(RU_Russia::class);
        $this->call(RW_Rwanda::class);
        $this->call(SA_SaudiArabia::class);
        $this->call(SB_SolomonIslands::class);
        $this->call(SC_Seychelles::class);
        $this->call(SD_Sudan::class);
        $this->call(SE_Sweden::class);
        $this->call(SG_Singapore::class);
        $this->call(SH_SaintHelena::class);
        $this->call(SI_Slovenia::class);
        $this->call(SJ_SvalbardandJanMayen::class);
        $this->call(SK_Slovakia::class);
        $this->call(SL_SierraLeone::class);
        $this->call(SM_SanMarino::class);
        $this->call(SN_Senegal::class);
        $this->call(SO_Somalia::class);
        $this->call(SR_Suriname::class);
        $this->call(ST_SaoTomeandPrincipe::class);
        $this->call(SV_ElSalvador::class);
        $this->call(SY_Syria::class);
        $this->call(SZ_Swaziland::class);
        $this->call(TC_TurksandCaicosIslands::class);
        $this->call(TD_Chad::class);
        $this->call(TF_FrenchSouthernTerritories::class);
        $this->call(TG_Togo::class);
        $this->call(TH_Thailand::class);
        $this->call(TJ_Tajikistan::class);
        $this->call(TK_Tokelau::class);
        $this->call(TL_TimorLeste::class);
        $this->call(TM_Turkmenistan::class);
        $this->call(TN_Tunisia::class);
        $this->call(TO_Tonga::class);
        $this->call(TR_Turkey::class);
        $this->call(TT_TrinidadandTobago::class);
        $this->call(TV_Tuvalu::class);
        $this->call(TW_Taiwan::class);
        $this->call(TZ_Tanzania::class);
        $this->call(UA_Ukraine::class);
        $this->call(UG_Uganda::class);
        $this->call(UM_USMinorOutlyingIslands::class);
        $this->call(US_UnitedStatesofAmerica::class);
        $this->call(UY_Uruguay::class);
        $this->call(UZ_Uzbekistan::class);
        $this->call(VA_VaticanCity::class);
        $this->call(VC_SaintVincentandGrenadines::class);
        $this->call(VE_Venezuela::class);
        $this->call(VG_BritishVirginIslands::class);
        $this->call(VI_VirginIslandsUS::class);
        $this->call(VN_Vietnam::class);
        $this->call(VU_Vanuatu::class);
        $this->call(WF_WallisandFutunaIslands::class);
        $this->call(WS_Samoa::class);
        $this->call(YE_Yemen::class);
        $this->call(YT_Mayotte::class);
        $this->call(ZA_SouthAfrica::class);
        $this->call(ZM_Zambia::class);
        $this->call(ZW_Zimbabwe::class);

    }
}
